version: '3.1'

services:
  mysql1:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./mysql/scripts:/docker-entrypoint-initdb.d
    environment:
      MYSQL_PORT: '3306'
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: banco
    ports:
      - 3306:3306
    expose:
      - '3306'

  backend:
    image: 'macevedg/banco-backend'
    restart: always
    build: 
      context: ./banco-backend
      dockerfile: back.Dockerfile
    working_dir: /app
    volumes:
      - ./banco-backend:/app
      - ~/.m2:/root/.m2
    expose:
      - "8080"
    ports:
      - 8080:8080
    depends_on:
      - mysql1
    
    command: mvn clean spring-boot:run

  frontend:
    image: 'macevedg/banco-frontend'
    build: 
      context: './banco-frontend'
      dockerfile: front.Dockerfile
    ports:
      - 3000:80
    depends_on: 
    - "backend"
    links:
      - "backend"

      
