version: '3.1'

services:

  mysql1:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./mysql/scripts:/docker-entrypoint-initdb.d
    environment:
      MYSQL_PORT: 3306
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: banco

  backend:
    image: 'macevedg/banco-backend'
    restart: always
    build: ./banco-backend
    working_dir: /app
    volumes:
      - ./banco-backend:/app
      - ~/.m2:/root/.m2
    expose:
      - "8080"
    command: mvn clean spring-boot:run
    depends_on:
      - mysql

  frontend:
    image: 'macevedg/banco-frontend'
    build: './banco-frontend'
    ports:
      - 3000:80
    depends_on: 
    - mysql1
    - backend
      
